enum ActionKind {
    Walking,
    Idle,
    Jumping,
    Dead
}
namespace SpriteKind {
    export const Ground = SpriteKind.create()
    export const Cloud = SpriteKind.create()
}
function initGround () {
    ground1 = sprites.create(img`
        ...................................................................................cccc...........................................................................
        ..................................................................................cbbbbc..........................................................................
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbccccccccccccccccc....ccccccccccccccccccccccccccccccccccccccccccccccccccccc
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbccccbbcbbbbbbbbbbbbbbbbbbbbbbbcbbccccbbbbbbbbbbbbbbbbbbbbbbbbbccccbbcbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbccccbbcbbbbbbbbbbbcbbcccbbbbbbbbbbbbbbbbbcbbcccbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbccccbcbbbbbbbcbbbbbbbbbbbbbbccbcbbbbbbbbccccbbcbbbbbccccbbcbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbccccbbcbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        `, SpriteKind.Ground)
    ground2 = sprites.create(img`
        .....................................................cccc..................cccc...................................................................................
        ....................................................cbbbbc................cbbbbc..................................................................................
        ccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbccccccccccccccccbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbcccbbcbbbbbbbbbbbbbbbbbcccbbcbbbbbbbbbbbcbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbcbbccccbbbbbbbbbbbbbbbbbbbbbbbbbccccbbcbbbbbbbbbbbbbbbbbbbbbbbcbbccccbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbcbbccccbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbcbbccccbbbbbcbbccccbbbbbbbbcbccbbbbbbbbbbbbbbcbbbbbbbcbccccbbbbbbbbbbbbbbbbbbbbbbbbbcbbccccbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        `, SpriteKind.Ground)
    ground1.setPosition(scene.screenWidth() / 2, 120)
    ground2.setPosition(ground1.x + scene.screenWidth(), 120)
    ground1.vx = -100
    ground2.vx = -100
    ground1.z = 2
    ground2.z = 2
}
function initRaptor () {
    raptor = sprites.create(img`
        ................................
        ................................
        ................................
        .......................f........
        ......................ff........
        ..............ffffff.fff........
        .............fffffffffff........
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffff.......
        .............ffffffffffff.......
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffffff.....
        .............ffffffffffff.......
        ............ffffffffffff........
        ...........ffffffffffff.........
        .......fff.......fff............
        .......fffffffffffff............
        .......fff.....ffff.............
        ..............ffff..............
        ..............fff...............
        .......fff...f..f...............
        ......fffffff....f..............
        ......ffff........f....f........
        ......ff...........ff.ff........
        ......ff...........fffff........
        ......f............ffff.........
        ....................ff..........
        ................................
        ................................
        ................................
        `, SpriteKind.Player)
    run = animation.createAnimation(ActionKind.Walking, 100)
    run.addAnimationFrame(img`
        ................................
        ................................
        ................................
        .......................f........
        ......................ff........
        ..............ffffff.fff........
        .............fffffffffff........
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffff.......
        .............ffffffffffff.......
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffffff.....
        .............ffffffffffff.......
        ............ffffffffffff........
        ...........ffffffffffff.........
        .......fff.......fff............
        .......fffffffffffff............
        .......fff.....ffff.............
        ..............ffff..............
        ..............fff...............
        .......fff...f..f...............
        ......fffffff....f..............
        ......ffff........f....f........
        ......ff...........ff.ff........
        ......ff...........fffff........
        ......f............ffff.........
        ....................ff..........
        ................................
        ................................
        ................................
        `)
    run.addAnimationFrame(img`
        ................................
        ................................
        ................................
        .......................f........
        ......................ff........
        ..............ffffff.fff........
        .............fffffffffff........
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffff.......
        .............ffffffffffff.......
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffffff.....
        .............ffffffffffff.......
        ............ffffffffffff........
        ...........ffffffffffff.........
        .......fff.......fff............
        .......fffffffffffff............
        .......fff.....ffff.............
        .............fffff..............
        ..............fff...............
        ...............f................
        ...............f................
        ...............f................
        ...............f................
        ..............fff...............
        ..............fff...............
        ..............fffff.............
        ..............ffffff............
        ................................
        ................................
        `)
    animation.attachAnimation(raptor, run)
    jump = animation.createAnimation(ActionKind.Jumping, 150)
    jump.addAnimationFrame(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ............fffffff.............
        ...........f999999ff............
        ..........ffffffff9ff...........
        .........ff999999ff9ff..........
        ........ff9ffffff9ff9ff.........
        .......ff9ff9999ff9ff9ff........
        ......ff9ff9ffff9ff9ff9ff.......
        .....ff9ff9ff99ff9ff9ff9ff......
        ....ff9ff9ff9ff9ff9ff9ff9ff.....
        ....f9ff9ff9ffff9ff9ff9ff9f.....
        ....f9f9ff9ff99ff9ff9ff9f9f.....
        ....f9f9f9ff9ff9ff9ff9f9f9f.....
        ....f9f9ff9ff9fff9ff9ff9f9f.....
        ....f9ff9ff9ff9f9ff9ff9ff9f.....
        ....ff9ff9ff9ff9ff9ff9ff9ff.....
        .....ff9ff9ff9fff9ff9ff9ff......
        ......ff9ff9ff9f9ff9ff9ff.......
        .......ff9ff9ff9ff9ff9ff........
        ........ff9ff9fff9ff9ff.........
        .........ff9ff999ff9ff..........
        ..........ff9fffff9ff...........
        ...........ff99999ff............
        ............fffffff.............
        ................................
        ................................
        ................................
        ................................
        `)
    jump.addAnimationFrame(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ............fffffff.............
        ...........ff99999ff............
        ..........ff9fffff9ff...........
        .........ff9ff999ff9ff..........
        ........ff9ff9fff9ff9ff.........
        .......ff9ff9ff9ff9ff9ff........
        ......ff9ff9ff9f9ff9ff9ff.......
        .....ff9ff9ff9fff9ff9ff9ff......
        ....ff9ff9ff9ff9ff9ff9f9f9f.....
        ....f9ff9ff9ff9f9ff9f9f9f9f.....
        ....f9f9ff9ff9ff9ff9f9f9f9f.....
        ....f9f9f9ff9ff9ff9ff9f9f9f.....
        ....f9f9ff9ff9fff9ff9ff9f9f.....
        ....f9ff9ff9ff9f9ff9ff9ff9f.....
        ....ff9ff9ff9ff9ff9ff9ff9ff.....
        .....ff9ff9ff9fff9ff9ff9ff......
        ......ff9ff9ff9f9ff9ff9ff.......
        .......ff9ff9ff9ff9ff9ff........
        ........ff9ff9fff9ff9ff.........
        .........ff9ff999ff9ff..........
        ..........ff9fffff9ff...........
        ...........ff99999ff............
        ............fffffff.............
        ................................
        ................................
        ................................
        ................................
        `)
    jump.addAnimationFrame(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ............fffffff.............
        ...........ff99999ff............
        ..........ff9fffff9ff...........
        .........ff9ff999ff9ff..........
        ........ff9ff9fff9ff9ff.........
        .......ff9ff9ff9ff9ff9ff........
        ......ff9ff9ff9f9ff9ff9ff.......
        .....ff9ff9ff9fff9ff9ff9ff......
        ....ff9ff9ff9ff9ff9ff9ff9ff.....
        ....f9ff9ff9ff9f9ff9ff9ff9f.....
        ....f9f9ff9ff9fff9ff9ff9f9f.....
        ....f9f9f9ff9ff9ff9ff9f9f9f.....
        ....f9f9ff9ff9ff99ff9ff9f9f.....
        ....f9ff9ff9ff9ffff9ff9ff9f.....
        ....ff9ff9ff9ff9ff9ff9ff9ff.....
        .....ff9ff9ff9ff99ff9ff9ff......
        ......ff9ff9ff9ffff9ff9ff.......
        .......ff9ff9ff9999ff9ff........
        ........ff9ff9ffffff9ff.........
        .........ff9ff999999ff..........
        ..........ff9ffffffff...........
        ...........ff999999f............
        ............fffffff.............
        ................................
        ................................
        ................................
        ................................
        `)
    jump.addAnimationFrame(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ............fffffff.............
        ...........ff99999ff............
        ..........ff9fffff9ff...........
        .........ff9ff999ff9ff..........
        ........ff9ff9fff9ff9ff.........
        .......ff9ff9ff9ff9ff9ff........
        ......ff9ff9ff9f9ff9ff9ff.......
        .....ff9ff9ff9fff9ff9ff9ff......
        ....ff9ff9ff9ff9ff9ff9ff9ff.....
        ....f9ff9ff9ff9f9ff9ff9ff9f.....
        ....f9f9ff9ff9fff9ff9ff9f9f.....
        ....f9f9f9ff9ff9ff9ff9f9f9f.....
        ....f9f9f9f9ff9ff9ff9ff9f9f.....
        ....f9f9f9f9ff9f9ff9ff9ff9f.....
        ....f9f9f9ff9ff9ff9ff9ff9ff.....
        .....ff9ff9ff9fff9ff9ff9ff......
        ......ff9ff9ff9f9ff9ff9ff.......
        .......ff9ff9ff9ff9ff9ff........
        ........ff9ff9fff9ff9ff.........
        .........ff9ff999ff9ff..........
        ..........ff9fffff9ff...........
        ...........ff99999ff............
        ............fffffff.............
        ................................
        ................................
        ................................
        ................................
        `)
    animation.attachAnimation(raptor, jump)
    dead = animation.createAnimation(ActionKind.Dead, 200)
    dead.addAnimationFrame(img`
        ................................
        ................................
        ................................
        .......................f........
        ......................ff........
        ..............ffffff.fff........
        .............fffffffffff........
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffff.......
        .............ffffffffffff.......
        ............fffffffffffff.......
        ...........ffffffffffffff.......
        ..............fffffffffffff.....
        .............ffffffffffff.......
        ............ffffffffffff........
        ......fffffffffffffffff.........
        .....ffffff.......ff.....fff....
        ....fffffff......fffffffffff....
        .........fff....ffff.....fff....
        ............fffffff.f...........
        .......fffff...fff...f..........
        ......ffffff..f.......ff........
        .....fffffff.f........ffff......
        ..........fff..........fff......
        .......................fff......
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `)
    animation.attachAnimation(raptor, dead)
    raptor.z = 3
    raptor.setPosition(15, 94)
}
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    if (raptor.y == 94 && end == 0) {
        raptor.vy = -160
        animation.setAction(raptor, ActionKind.Jumping)
        music.jumpUp.play()
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    end = 1
    animation.setAction(raptor, ActionKind.Dead)
    pause(50)
})
let cloud: Sprite = null
let cactus: Sprite = null
let choice = 0
let dead: animation.Animation = null
let jump: animation.Animation = null
let run: animation.Animation = null
let raptor: Sprite = null
let ground2: Sprite = null
let ground1: Sprite = null
let end = 0
let idle = null
game.setDialogCursor(img`
    ................................
    ..11111111111111111111fff11111..
    .11111111111111111111fffff11111.
    1111111111111fffffffffffff111111
    111111111111ffffffffffffff111111
    11111111111fffffffffffffff111111
    1111111111fffffffffffffffff11111
    111111111ffffffffffffffffff11111
    11111111fffffffffffffffffff11111
    11111111fffffffffffffffffff11111
    1111111111fffffffffffffffff11111
    111111111fffffffffffffffffff1111
    111111111ffffffffffffffffffff111
    111111111ffffffffffffffffffff111
    1111111111fffffffffffffffffff111
    111111ffffffffffffffffffffff1111
    11111fffffffffffffffffffff111111
    11111ffffffffffffffffffff1111111
    11111fffffffffffffffffff11111111
    11111fffffffffffffffff1111111111
    11111ffffffffffffffff11111111111
    11111fffffffffffffff111111111111
    1111ffffffffffffffff11fff1111111
    1111ffffffffffffffffffffff111111
    1111ffffffffffffffffffffff111111
    1111ffffffffff11ffffffffff111111
    1111fffffff111111fffffffff111111
    1111ffffff1111111fffffffff111111
    1111fffff11111111ffffffff1111111
    11111ffff111111111ffffff11111111
    .111111111111111111ffff11111111.
    ..1111111111111111111111111111..
    `)
game.splash("Night Hill Run")
scene.setBackgroundColor(12)
initGround()
initRaptor()
info.setScore(0)
end = 0
game.showLongText("Press any button to spin jump.", DialogLayout.Top)
game.onUpdate(function () {
    if (raptor.y < 94) {
        raptor.ay = 400
    } else {
        raptor.ay = 0
        raptor.y = 94
        if (end == 0) {
            animation.setAction(raptor, ActionKind.Walking)
        }
    }
})
game.onUpdateInterval(50, function () {
    info.changeScoreBy(1)
})
game.onUpdateInterval(1000, function () {
    ground1.vx += -1
    ground2.vx += -1
})
game.onUpdateInterval(1000, function () {
    choice = randint(0, 4)
    if (choice == 0) {
        cactus = sprites.createProjectileFromSide(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...........1....................
            ...........1....................
            ..........11....................
            ..........11....................
            ..........11....................
            .........111.1..1...............
            .........111.1.111..............
            ........1111111111..............
            ........11111111111.............
            ........11111111111.............
            `, ground1.vx, 0)
        cactus.y = 94
        cactus.z = 2
    } else if (choice == 1) {
        cactus = sprites.createProjectileFromSide(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...........1....................
            ...........1....................
            ..........11....................
            ..........11....................
            ..........11....................
            .........111.1..1...............
            .........111.1.111..............
            ........1111111111..............
            ........11111111111.............
            ........11111111111.............
            `, ground1.vx, 0)
        cactus.y = 94
        cactus.z = 2
    } else if (choice == 2) {
        cactus = sprites.createProjectileFromSide(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...........1.....11.............
            ...........1...111..............
            ..........11....111.............
            .........111.1..111.............
            .........111.1.111111...........
            ........1111111111111...........
            ........1111111111111...........
            ........1111111111111...........
            `, ground1.vx, 0)
        cactus.y = 94
        cactus.z = 2
    }
})
game.onUpdateInterval(1500, function () {
    if (Math.percentChance(40)) {
        cloud = sprites.createProjectileFromSide(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................bbbbbbb.........
            ...............bb11111b.........
            .............bbb111111bbb.......
            .............b111111b111bbbb....
            .............b1111111b11111b....
            ..........bbbb11111111bb111bbb..
            .........bb111111111111111111b..
            .....bbbbb1111111111111111111bb.
            .....b111111111111111111111111b.
            .bbbbb11b1111111111111111111111b
            bb1111111bbbbbbbbbbbbbbbbbbbbbbb
            ..bbbbbbb.......................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `, ground1.vx / 4, 0)
        cloud.y = randint(20, 60)
        cloud.setKind(SpriteKind.Cloud)
        cloud.z = 1
    }
})
forever(function () {
    if (ground2.x < -1 * (scene.screenWidth() / 2)) {
        ground2.x = ground1.x + scene.screenWidth()
    }
})
forever(function () {
    if (ground1.x < -1 * (scene.screenWidth() / 2)) {
        ground1.x = ground2.x + scene.screenWidth()
    }
})
